/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import accesoADatos.InscripcionData;
import accesoADatos.MateriaData;
import entidades.Alumno;
import entidades.Materia;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hugo
 */
public class viewListadoDeAlumnosXMateria extends javax.swing.JInternalFrame {

    private MateriaData md;
    private InscripcionData id;
    private Materia mat = null;
    public DefaultTableModel model = new DefaultTableModel(); //declaro para manipular la tabla
    /**
     * Creates new form viewListadoDeAlumnos
     */
    public viewListadoDeAlumnosXMateria() {
        initComponents();
        model = (DefaultTableModel) this.tblAlumnos.getModel(); //manipulo la tabla generada por interfaz
        md = new MateriaData();
        List<Materia> materias = new ArrayList<>();
        materias = md.listarMaterias();
        for (Materia m : materias) {
            this.cbxMaterias.addItem(m);
        }
    }
    
    public void eliminarFilas() {
        while (model.getRowCount() > 0) {
            int i = model.getRowCount();
            model.removeRow(i - 1);
        }
    }
    
    public void obtenerAlumnos(){
        id = new InscripcionData();
        mat = (Materia) cbxMaterias.getSelectedItem();
        for (Alumno alum : id.obtenerAlumnosXMateria(mat.getIdMateria())) {
            model.addRow(new Object[]{alum.getIdAlumno(), alum.getDni(), alum.getApellido(), alum.getNombre()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtListadoDeAlumnosPorMateria = new javax.swing.JScrollPane();
        tblAlumnos = new javax.swing.JTable();
        lblListadoDeAlumnosPorMateria = new javax.swing.JLabel();
        lblSelMateria = new javax.swing.JLabel();
        cbxMaterias = new javax.swing.JComboBox<>();
        btnSalir = new javax.swing.JButton();

        tblAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "DNI", "Apellido", "Nombre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtListadoDeAlumnosPorMateria.setViewportView(tblAlumnos);

        lblListadoDeAlumnosPorMateria.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblListadoDeAlumnosPorMateria.setText("Listado de alumnos por materia");

        lblSelMateria.setText("Seleccione una materia:");

        cbxMaterias.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxMateriasItemStateChanged(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblSelMateria)
                                .addGap(18, 18, 18)
                                .addComponent(cbxMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addComponent(lblListadoDeAlumnosPorMateria)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jtListadoDeAlumnosPorMateria, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSalir)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblListadoDeAlumnosPorMateria)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSelMateria)
                    .addComponent(cbxMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jtListadoDeAlumnosPorMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(btnSalir))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void cbxMateriasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxMateriasItemStateChanged
        eliminarFilas();
        obtenerAlumnos();
    }//GEN-LAST:event_cbxMateriasItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<Materia> cbxMaterias;
    private javax.swing.JScrollPane jtListadoDeAlumnosPorMateria;
    private javax.swing.JLabel lblListadoDeAlumnosPorMateria;
    private javax.swing.JLabel lblSelMateria;
    private javax.swing.JTable tblAlumnos;
    // End of variables declaration//GEN-END:variables
}
