/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import accesoADatos.AlumnoData;
import accesoADatos.InscripcionData;
import entidades.Alumno;
import entidades.Inscripcion;
import entidades.Materia;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hugo
 */
public class viewFormularioDeInscripcion extends javax.swing.JInternalFrame {

    private AlumnoData ad;
    private InscripcionData id;
    private Alumno a = null;
    private Materia m = null;
    private List<Materia> materias = new ArrayList<>();
    public DefaultTableModel model = new DefaultTableModel(); //declaro para manipular la tabla

    /**
     * Creates new form viewFormularioDeInscripcion
     */
    public viewFormularioDeInscripcion() {
        initComponents();
        model = (DefaultTableModel) this.tblInscripciones.getModel(); //manipulo la tabla generada por interfaz
        ad = new AlumnoData();
        id = new InscripcionData();
        List<Alumno> alumnos = new ArrayList<>();
        alumnos = ad.listarAlumnos();
        for (Alumno a : alumnos) {
            this.cbxAlumnos.addItem(a);
        }
    }

    public void listarAlumnos() {
        a = (Alumno) cbxAlumnos.getSelectedItem();
        if (this.jrbMatInsc.isSelected()) {
            materias = id.obtenerMateriasCursadas(a.getIdAlumno());
            cargarInscripcionesSegunAlumno(materias);
        } else {
            materias = id.obtenerMateriasNOCursadas(a.getIdAlumno());
            cargarInscripcionesSegunAlumno(materias);
        }
    }

    public void cargarInscripcionesSegunAlumno(List<Materia> materias) {
        for (Materia mat : materias) {
            model.addRow(new Object[]{mat.getIdMateria(), mat.getNombre(), mat.getAño()});
        }
    }

    public void eliminarFilas() {
        while (model.getRowCount() > 0) {
            int i = model.getRowCount();
            model.removeRow(i - 1);
        }
    }

    public void inscribir() {
        if (this.tblInscripciones.getSelectedRowCount() == 1 && this.jrbMatNoInsc.isSelected()) {
            m = new Materia();
            m.setIdMateria((int) tblInscripciones.getValueAt(tblInscripciones.getSelectedRow(), 0));
            //materia solo recupera id por velocidad nomas 

            id.guardarInscripcion(new Inscripcion(0, a, m));
            eliminarFilas();
            this.jrbMatNoInsc.doClick();
        }
    }

    public void AnularInscripcion() {
        if (this.tblInscripciones.getSelectedRowCount() == 1 && this.jrbMatInsc.isSelected()) {
            m = new Materia();
            m.setIdMateria((int) tblInscripciones.getValueAt(tblInscripciones.getSelectedRow(), 0));
            //materia solo recupera id por velocidad nomas 

            id.borrarInscripcionMateriaAlumno(a.getIdAlumno(), m.getIdMateria());
            eliminarFilas();
            this.jrbMatInsc.doClick();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        lblFormularioDeInscripcion = new javax.swing.JLabel();
        lblSeleccioneUnAlumno = new javax.swing.JLabel();
        lblListadoMaterias = new javax.swing.JLabel();
        cbxAlumnos = new javax.swing.JComboBox<>();
        jtAlumnos = new javax.swing.JScrollPane();
        tblInscripciones = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jrbMatInsc = new javax.swing.JRadioButton();
        jrbMatNoInsc = new javax.swing.JRadioButton();
        btnInscribir = new javax.swing.JButton();
        btnAnularInsc = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setTitle("Formulario de Inscripción");

        lblFormularioDeInscripcion.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblFormularioDeInscripcion.setText("Formulario de Inscripcion");

        lblSeleccioneUnAlumno.setText("Seleccione un alumno:");

        lblListadoMaterias.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblListadoMaterias.setText("Listado de Materias");

        cbxAlumnos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxAlumnosItemStateChanged(evt);
            }
        });

        tblInscripciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Año"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtAlumnos.setViewportView(tblInscripciones);

        buttonGroup.add(jrbMatInsc);
        jrbMatInsc.setText("Materias inscriptas");
        jrbMatInsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbMatInscActionPerformed(evt);
            }
        });

        buttonGroup.add(jrbMatNoInsc);
        jrbMatNoInsc.setSelected(true);
        jrbMatNoInsc.setText("Materias no inscriptas");
        jrbMatNoInsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbMatNoInscActionPerformed(evt);
            }
        });

        btnInscribir.setText("Inscribir");
        btnInscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInscribirActionPerformed(evt);
            }
        });

        btnAnularInsc.setText("Anular Inscripción");
        btnAnularInsc.setEnabled(false);
        btnAnularInsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnularInscActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblFormularioDeInscripcion)
                .addGap(119, 119, 119))
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(btnInscribir)
                .addGap(40, 40, 40)
                .addComponent(btnAnularInsc)
                .addGap(52, 52, 52)
                .addComponent(btnSalir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(lblListadoMaterias)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jrbMatInsc)
                                        .addGap(63, 63, 63)
                                        .addComponent(jrbMatNoInsc)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblSeleccioneUnAlumno)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                                        .addComponent(cbxAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jtAlumnos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblFormularioDeInscripcion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSeleccioneUnAlumno)
                    .addComponent(cbxAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblListadoMaterias)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbMatInsc)
                    .addComponent(jrbMatNoInsc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInscribir)
                    .addComponent(btnAnularInsc)
                    .addComponent(btnSalir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxAlumnosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxAlumnosItemStateChanged
        eliminarFilas();
        listarAlumnos();
    }//GEN-LAST:event_cbxAlumnosItemStateChanged

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void jrbMatInscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbMatInscActionPerformed
        eliminarFilas();
        listarAlumnos();
        this.btnInscribir.setEnabled(false);
        this.btnAnularInsc.setEnabled(true);
    }//GEN-LAST:event_jrbMatInscActionPerformed

    private void jrbMatNoInscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbMatNoInscActionPerformed
        eliminarFilas();
        listarAlumnos();
        this.btnInscribir.setEnabled(true);
        this.btnAnularInsc.setEnabled(false);
    }//GEN-LAST:event_jrbMatNoInscActionPerformed

    private void btnInscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInscribirActionPerformed
        inscribir();
    }//GEN-LAST:event_btnInscribirActionPerformed

    private void btnAnularInscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnularInscActionPerformed
        AnularInscripcion();
    }//GEN-LAST:event_btnAnularInscActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnularInsc;
    private javax.swing.JButton btnInscribir;
    private javax.swing.JButton btnSalir;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JComboBox<Alumno> cbxAlumnos;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton jrbMatInsc;
    private javax.swing.JRadioButton jrbMatNoInsc;
    private javax.swing.JScrollPane jtAlumnos;
    private javax.swing.JLabel lblFormularioDeInscripcion;
    private javax.swing.JLabel lblListadoMaterias;
    private javax.swing.JLabel lblSeleccioneUnAlumno;
    private javax.swing.JTable tblInscripciones;
    // End of variables declaration//GEN-END:variables
}
