/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import accesoADatos.AlumnoData;
import accesoADatos.InscripcionData;
import entidades.Alumno;
import entidades.Inscripcion;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hugo
 */
public class viewManipulacionDeNotas extends javax.swing.JInternalFrame {

    private Alumno a = null;
    private AlumnoData ad;
    private InscripcionData id;
    public DefaultTableModel model = new DefaultTableModel(); //declaro para manipular la tabla

    /**
     * Creates new form viewManipulacionDeNotas
     */
    public viewManipulacionDeNotas() {
        initComponents();
        model = (DefaultTableModel) this.tblInscripciones.getModel(); //manipulo la tabla generada por interfaz
        ad = new AlumnoData();
        id = new InscripcionData();
        List<Alumno> alumnos = new ArrayList<>();
        alumnos = ad.listarAlumnos();
        for (Alumno a : alumnos) {
            this.cbxAlumnos.addItem(a);
        }
    }

    public void eliminarFilas() {
        while (model.getRowCount() > 0) {
            int i = model.getRowCount();
            model.removeRow(i - 1);
        }
    }

    public void listarMateriasCursadas() {
        a = (Alumno) cbxAlumnos.getSelectedItem();
        id.obtenerInscripcionesPorAlumno(a.getIdAlumno());

        for (Inscripcion insc : id.obtenerInscripcionesPorAlumno(a.getIdAlumno())) {
            model.addRow(new Object[]{insc.getMateria().getIdMateria(), insc.getMateria().getNombre(), insc.getNota()});
        }
    }

    public void guardarNota() {
        if (this.tblInscripciones.getSelectedRowCount() == 1) {
            id.actualizarNota(a.getIdAlumno(), (int) tblInscripciones.getValueAt(tblInscripciones.getSelectedRow(), 0), (Double) tblInscripciones.getValueAt(tblInscripciones.getSelectedRow(), 2));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtListaDeNotasDeAlumnos = new javax.swing.JScrollPane();
        tblInscripciones = new javax.swing.JTable();
        lblCargaDeNotas = new javax.swing.JLabel();
        lblSeleccioneAlumno = new javax.swing.JLabel();
        cbxAlumnos = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        Separator = new javax.swing.JSeparator();

        setTitle("Carga de Notas");

        tblInscripciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Nota"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtListaDeNotasDeAlumnos.setViewportView(tblInscripciones);

        lblCargaDeNotas.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblCargaDeNotas.setText("Carga de Notas");

        lblSeleccioneAlumno.setText("Seleccione un alumno:");

        cbxAlumnos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxAlumnosItemStateChanged(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtListaDeNotasDeAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(btnGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addGap(90, 90, 90))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblSeleccioneAlumno)
                        .addGap(18, 18, 18)
                        .addComponent(cbxAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(lblCargaDeNotas)))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Separator)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblCargaDeNotas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Separator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSeleccioneAlumno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtListaDeNotasDeAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnSalir))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void cbxAlumnosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxAlumnosItemStateChanged
        eliminarFilas();
        listarMateriasCursadas();
    }//GEN-LAST:event_cbxAlumnosItemStateChanged

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        guardarNota();
    }//GEN-LAST:event_btnGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator Separator;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<Alumno> cbxAlumnos;
    private javax.swing.JScrollPane jtListaDeNotasDeAlumnos;
    private javax.swing.JLabel lblCargaDeNotas;
    private javax.swing.JLabel lblSeleccioneAlumno;
    private javax.swing.JTable tblInscripciones;
    // End of variables declaration//GEN-END:variables
}
