/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import accesoADatos.AlumnoData;
import accesoADatos.MateriaData;

/**
 *
 * @author Hugo
 */
public class viewMenu extends javax.swing.JFrame {
    private AlumnoData ad;
    private MateriaData md;
    /**
     * Creates new form viewMenu
     */
    public viewMenu() {
        initComponents();
        ad = new AlumnoData();
        md = new MateriaData();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        mnbMenu = new javax.swing.JMenuBar();
        mnuAlumnos = new javax.swing.JMenu();
        mniInscribirAlumno = new javax.swing.JMenuItem();
        mnuMaterias = new javax.swing.JMenu();
        mniInscribirMaterias = new javax.swing.JMenuItem();
        mnuAdministracion = new javax.swing.JMenu();
        mniFormularioDeInscripciones = new javax.swing.JMenuItem();
        mniManipulacionDeNotas = new javax.swing.JMenuItem();
        mnuConsultas = new javax.swing.JMenu();
        mniListadoDeAlumnos = new javax.swing.JMenuItem();
        mnuSalir = new javax.swing.JMenu();
        mniSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 579, Short.MAX_VALUE)
        );

        mnuAlumnos.setText("Alumno");

        mniInscribirAlumno.setText("Formulario de Alumno");
        mniInscribirAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniInscribirAlumnoActionPerformed(evt);
            }
        });
        mnuAlumnos.add(mniInscribirAlumno);

        mnbMenu.add(mnuAlumnos);

        mnuMaterias.setText("Materia");

        mniInscribirMaterias.setText("Formulario de Materia");
        mniInscribirMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniInscribirMateriasActionPerformed(evt);
            }
        });
        mnuMaterias.add(mniInscribirMaterias);

        mnbMenu.add(mnuMaterias);

        mnuAdministracion.setText("Administración");

        mniFormularioDeInscripciones.setText("Manejo de Inscripciones");
        mniFormularioDeInscripciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniFormularioDeInscripcionesActionPerformed(evt);
            }
        });
        mnuAdministracion.add(mniFormularioDeInscripciones);

        mniManipulacionDeNotas.setText("Manipulación de notas");
        mniManipulacionDeNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniManipulacionDeNotasActionPerformed(evt);
            }
        });
        mnuAdministracion.add(mniManipulacionDeNotas);

        mnbMenu.add(mnuAdministracion);

        mnuConsultas.setText("Consultas");

        mniListadoDeAlumnos.setText("Alumnos por Materia");
        mniListadoDeAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniListadoDeAlumnosActionPerformed(evt);
            }
        });
        mnuConsultas.add(mniListadoDeAlumnos);

        mnbMenu.add(mnuConsultas);

        mnuSalir.setText("Salir");

        mniSalir.setText("Salir");
        mniSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniSalirActionPerformed(evt);
            }
        });
        mnuSalir.add(mniSalir);

        mnbMenu.add(mnuSalir);

        setJMenuBar(mnbMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniSalirActionPerformed
    this.dispose();
    }//GEN-LAST:event_mniSalirActionPerformed

    private void mniInscribirAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniInscribirAlumnoActionPerformed
        escritorio.removeAll();
        escritorio.repaint();

        viewInscribirAlumno ia = new viewInscribirAlumno(ad);
        ia.setVisible(true);
        escritorio.add(ia);
        escritorio.moveToFront(ia);
    }//GEN-LAST:event_mniInscribirAlumnoActionPerformed

    private void mniInscribirMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniInscribirMateriasActionPerformed
        escritorio.removeAll();
        escritorio.repaint();

        viewInscribirMateria im = new viewInscribirMateria(md);
        im.setVisible(true);
        escritorio.add(im);
        escritorio.moveToFront(im);
    }//GEN-LAST:event_mniInscribirMateriasActionPerformed

    private void mniFormularioDeInscripcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniFormularioDeInscripcionesActionPerformed
        escritorio.removeAll();
        escritorio.repaint();

        viewFormularioDeInscripcion fdi = new viewFormularioDeInscripcion();
        fdi.setVisible(true);
        escritorio.add(fdi);
        escritorio.moveToFront(fdi);
    }//GEN-LAST:event_mniFormularioDeInscripcionesActionPerformed

    private void mniManipulacionDeNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniManipulacionDeNotasActionPerformed
        escritorio.removeAll();
        escritorio.repaint();

        viewManipulacionDeNotas mdn = new viewManipulacionDeNotas();
        mdn.setVisible(true);
        escritorio.add(mdn);
        escritorio.moveToFront(mdn);
    }//GEN-LAST:event_mniManipulacionDeNotasActionPerformed

    private void mniListadoDeAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniListadoDeAlumnosActionPerformed
        escritorio.removeAll();
        escritorio.repaint();

        viewListadoDeAlumnosXMateria ldaxm = new viewListadoDeAlumnosXMateria();
        ldaxm.setVisible(true);
        escritorio.add(ldaxm);
        escritorio.moveToFront(ldaxm);
    }//GEN-LAST:event_mniListadoDeAlumnosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuBar mnbMenu;
    private javax.swing.JMenuItem mniFormularioDeInscripciones;
    private javax.swing.JMenuItem mniInscribirAlumno;
    private javax.swing.JMenuItem mniInscribirMaterias;
    private javax.swing.JMenuItem mniListadoDeAlumnos;
    private javax.swing.JMenuItem mniManipulacionDeNotas;
    private javax.swing.JMenuItem mniSalir;
    private javax.swing.JMenu mnuAdministracion;
    private javax.swing.JMenu mnuAlumnos;
    private javax.swing.JMenu mnuConsultas;
    private javax.swing.JMenu mnuMaterias;
    private javax.swing.JMenu mnuSalir;
    // End of variables declaration//GEN-END:variables
}
