/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Categoria;
import Modelo.Producto;
import java.util.TreeSet;

/**
 *
 * @author Hugo
 */
public class Ejercicio4 extends javax.swing.JFrame {

    public static TreeSet<Producto> productos = new TreeSet<>();

    /**
     * Creates new form Ejercicio4
     */
    public Ejercicio4() {
        initComponents();
        getProductos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuAdministracion = new javax.swing.JMenu();
        mniProductos = new javax.swing.JMenuItem();
        mnuConsultas = new javax.swing.JMenu();
        mniPorRubro = new javax.swing.JMenuItem();
        mniPorNombre = new javax.swing.JMenuItem();
        mniPorPrecio = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 600));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        mnuAdministracion.setText("Administración");

        mniProductos.setText("Productos");
        mniProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mniProductosMouseClicked(evt);
            }
        });
        mnuAdministracion.add(mniProductos);

        jMenuBar1.add(mnuAdministracion);

        mnuConsultas.setText("Consultas");

        mniPorRubro.setText("Por Rubro");
        mniPorRubro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniPorRubroActionPerformed(evt);
            }
        });
        mnuConsultas.add(mniPorRubro);

        mniPorNombre.setText("Por Nombre");
        mniPorNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mniPorNombreMouseClicked(evt);
            }
        });
        mniPorNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniPorNombreActionPerformed(evt);
            }
        });
        mnuConsultas.add(mniPorNombre);

        mniPorPrecio.setText("Por Precio");
        mniPorPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniPorPrecioActionPerformed(evt);
            }
        });
        mnuConsultas.add(mniPorPrecio);

        jMenuBar1.add(mnuConsultas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mniProductosMouseClicked
        //this.escritorio.add(this.jInternalFrame1);

        //this.jInternalFrame1.setVisible(true);

    }//GEN-LAST:event_mniProductosMouseClicked

    private void mniPorNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mniPorNombreMouseClicked

    }//GEN-LAST:event_mniPorNombreMouseClicked

    private void mniPorNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniPorNombreActionPerformed
        this.escritorio.removeAll();
        this.escritorio.repaint();
        ifrmConsultaPorNombre cpn = new ifrmConsultaPorNombre();

        cpn.setVisible(true);
        this.escritorio.add(cpn);
        this.escritorio.moveToFront(cpn);
    }//GEN-LAST:event_mniPorNombreActionPerformed

    private void mniPorPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniPorPrecioActionPerformed
        this.escritorio.removeAll();
        this.escritorio.repaint();
        ifrmConsultaPorPrecio cpp = new ifrmConsultaPorPrecio();

        cpp.setVisible(true);
        this.escritorio.add(cpp);
        this.escritorio.moveToFront(cpp);
    }//GEN-LAST:event_mniPorPrecioActionPerformed

    private void mniPorRubroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniPorRubroActionPerformed
        this.escritorio.removeAll();
        this.escritorio.repaint();
        ifrmConsultaPorRubro cpr = new ifrmConsultaPorRubro();

        cpr.setVisible(true);
        this.escritorio.add(cpr);
        this.escritorio.moveToFront(cpr);
    }//GEN-LAST:event_mniPorRubroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mniPorNombre;
    private javax.swing.JMenuItem mniPorPrecio;
    private javax.swing.JMenuItem mniPorRubro;
    private javax.swing.JMenuItem mniProductos;
    private javax.swing.JMenu mnuAdministracion;
    private javax.swing.JMenu mnuConsultas;
    // End of variables declaration//GEN-END:variables
    private void getProductos() {
        productos.add(new Producto(10, "Azucar 1 kg", 180.75, 5, Categoria.COMESTIBLE));
        productos.add(new Producto(12, "Yerba mate", 850, 10, Categoria.COMESTIBLE));
        productos.add(new Producto(5, "Aceite de girasol", 250, 5, Categoria.COMESTIBLE));
    }
}
